# install-services.yml

---
  - hosts: loadbalancers
    tasks:
      - name: Installing apache
        yum: name=httpd state=present

  - hosts: webservers
    become: true
    tasks:
      - name: Installing services
        yum:
          name: 
            - httpd 
            - php 
          state: present
